# Generated by Django 3.2.8 on 2022-04-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220427_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='api.comment', verbose_name='Корневой комментарий 3го уровня вложенности'),
        ),
    ]
